# Numpy Assignment


## Theoretical Questions:


### QUES - 1 :  Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does itenhance Python's capabilities for numerical operations?




### ANS - 1:

### Purpose and Advantages of NumPy in Scientific Computing and Data Analysis

NumPy is a powerful library in Python used for numerical and scientific computing. It provides an efficient way to handle large datasets and perform complex mathematical operations. The primary purpose of NumPy is to enable the use of **arrays** instead of traditional lists, which are optimized for speed and memory efficiency.

#### Key Advantages of NumPy:
1. **Efficient Multidimensional Arrays**: NumPy introduces the `ndarray`, a fast and space-efficient array object, which allows for easy manipulation of large datasets and supports operations on multiple dimensions (2D, 3D, etc.).
   
2. **Vectorized Operations**: NumPy allows for vectorized operations, meaning you can perform operations on entire arrays without the need for explicit loops, leading to faster execution.

3. **Broadcasting**: NumPy's broadcasting feature allows for operations on arrays of different shapes, making it easier to perform arithmetic between arrays without reshaping them manually.

4. **Mathematical Functions**: It includes a vast collection of mathematical functions, such as trigonometric, statistical, and linear algebra operations, which are optimized for performance.

5. **Interoperability**: NumPy integrates seamlessly with other libraries like Pandas, SciPy, and Matplotlib, making it ideal for data analysis and scientific computing workflows.

#### Enhancement of Python’s Capabilities:
While Python is a versatile programming language, its native data structures like lists are not optimized for numerical operations. NumPy fills this gap by providing high-performance arrays and tools for mathematical and statistical computations. Operations that would typically be slow with standard Python lists are much faster with NumPy due to its optimized C-based backend. As a result, NumPy significantly improves Python’s capability to handle scientific tasks, such as large-scale data analysis, simulations, and numerical problem-solving.


### QUES - 2 :  Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over theother?

### ANS - 2 : ### Comparison of `np.mean()` and `np.average()` in NumPy

Both `np.mean()` and `np.average()` are used to calculate the average of elements in an array, but they have distinct differences in terms of functionality and use cases.

#### `np.mean()`:
- **Purpose**: Calculates the arithmetic mean of the elements in an array.
- **Syntax**: `np.mean(a, axis=None, dtype=None, out=None, keepdims=False)`
- **Usage**: It computes the mean by summing up all the elements and dividing by the number of elements.
- **Flexibility**: `np.mean()` is simpler and does not require any additional arguments other than the array itself, making it ideal when a straightforward mean calculation is needed.

#### `np.average()`:
- **Purpose**: Computes the weighted average of the elements in an array. If no weights are provided, it behaves like `np.mean()`.
- **Syntax**: `np.average(a, axis=None, weights=None, returned=False)`
- **Usage**: The function accepts a `weights` parameter, allowing for weighted averages, where different elements in the array contribute differently to the result based on their assigned weights.
- **Flexibility**: `np.average()` is more versatile because it supports additional parameters like `weights` and `returned`, which can provide more control over how the average is computed.

### Key Differences:
1. **Weights**: `np.mean()` does not accept weights, whereas `np.average()` can accept weights to give different importance to the array elements.
2. **Flexibility**: `np.average()` provides additional functionality like returning both the weighted average and the sum of the weights if the `returned` argument is set to `True`.

### When to Use Each:
- **Use `np.mean()`** when you need a simple, unweighted arithmetic mean and don't require any additional control or customization.
  
- **Use `np.average()`** when you need a weighted average or if you need to track the sum of the weights in addition to the average.


### QUES - 3 :  Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2Darrays.

### ANS - 3:
### Methods for Reversing a NumPy Array Along Different Axes

NumPy provides several ways to reverse arrays, both for 1D and 2D arrays, by utilizing slicing and specific functions. Let's explore the methods used to reverse arrays along various axes.

### 1. **Reversing a 1D Array**

For a 1D array, reversing the array means flipping the order of the elements.

#### Method 1: Using Slicing (`[::-1]`)
This is the simplest way to reverse a 1D NumPy array.

**Example:**

```python
import numpy as np

# 1D array
arr = np.array([1, 2, 3, 4, 5])

# Reversing the 1D array
reversed_arr = arr[::-1]
print("Reversed 1D Array:", reversed_arr)
```

**Output:**
```
Reversed 1D Array: [5 4 3 2 1]
```

### 2. **Reversing a 2D Array**

In a 2D array, reversing can be done along different axes (rows or columns).

#### Method 1: Reversing Along Rows (Axis 1)

You can reverse the elements of each row of a 2D array. This means that for each row, the elements are reversed.

**Example:**

```python
# 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Reversing along rows (axis 1)
reversed_rows = arr_2d[:, ::-1]
print("Reversed Along Rows (Axis 1):")
print(reversed_rows)
```

**Output:**
```
Reversed Along Rows (Axis 1):
[[3 2 1]
 [6 5 4]
 [9 8 7]]
```

#### Method 2: Reversing Along Columns (Axis 0)

You can reverse the order of the rows in the array. This means that the rows will be flipped upside down.

**Example:**

```python
# Reversing along columns (axis 0)
reversed_columns = arr_2d[::-1, :]
print("Reversed Along Columns (Axis 0):")
print(reversed_columns)
```

**Output:**
```
Reversed Along Columns (Axis 0):
[[7 8 9]
 [4 5 6]
 [1 2 3]]
```

#### Method 3: Reversing Along Both Axes (Rows and Columns)

To reverse the array both along rows and columns, you can combine both slicing techniques.

**Example:**

```python
# Reversing along both axes
reversed_both = arr_2d[::-1, ::-1]
print("Reversed Along Both Axes:")
print(reversed_both)
```

**Output:**
```
Reversed Along Both Axes:
[[9 8 7]
 [6 5 4]
 [3 2 1]]
```

### Summary:
- **1D Array:** Reverse the array using slicing `[::-1]`.
- **2D Array (Rows):** Reverse each row using slicing `[:, ::-1]`.
- **2D Array (Columns):** Reverse the rows using slicing `[::-1, :]`.
- **2D Array (Both Axes):** Reverse both rows and columns using slicing `[::-1, ::-1]`.


### QUES - 4 :  How can you determine the data type of elements in a NumPy array? Discuss the importance of data typesin memory management and performance

### ANS - 4:


### Determining the Data Type of Elements in a NumPy Array

To determine the data type of elements in a NumPy array, you can use the `dtype` attribute. This attribute provides information about the type of data stored in the array.

**Example:**

```python
import numpy as np

# Creating a NumPy array
arr = np.array([1, 2, 3, 4])

# Determining the data type
print("Data type of elements:", arr.dtype)
```

**Output:**
```
Data type of elements: int64
```

In the example above, the data type of the elements is `int64`, indicating that each element is stored as a 64-bit integer.

### Importance of Data Types in Memory Management and Performance

#### 1. **Memory Management**
Data types play a crucial role in memory management because the amount of memory allocated for an array depends on its data type. NumPy allows you to choose from various data types, such as `int32`, `float64`, `complex128`, etc., which have different memory requirements.

For example:
- An `int32` data type uses 4 bytes per element.
- A `float64` data type uses 8 bytes per element.
  
By choosing a more compact data type (such as `int32` instead of `int64`), you can significantly reduce the memory consumption of large arrays, which is particularly useful when working with large datasets or on systems with limited memory.

#### 2. **Performance**
The data type of an array also affects performance. Operations on arrays with smaller data types are generally faster because:
- Less memory is accessed and transferred during calculations.
- The processor can handle smaller data types more efficiently, leading to faster execution of operations.

For example, using a smaller data type like `float32` instead of `float64` can improve performance when performing matrix operations or statistical calculations, especially when working with large datasets.

#### 3. **Precision**
Choosing the correct data type ensures that the precision of calculations is maintained. For example:
- Using `int32` for integer values in a range that does not require more than 32 bits will save memory.
- Using `float64` ensures that calculations with decimal numbers maintain higher precision, but it takes more memory.

#### 4. **Type Conversion**
In some cases, you may need to convert between data types (for example, from `int32` to `float64`) to avoid overflow or to maintain precision. NumPy provides functions like `astype()` for type conversion.

**Example:**

```python
# Converting data type
arr_float = arr.astype(np.float64)
print("Converted data type:", arr_float.dtype)
```

**Output:**
```
Converted data type: float64
```

### Conclusion:
- **`dtype` Attribute:** You can use the `.dtype` attribute to determine the data type of elements in a NumPy array.
- **Memory Efficiency:** Data types influence memory consumption; smaller types save memory.
- **Performance:** Choosing the right data type can improve the speed of operations.
- **Precision:** Selecting the appropriate data type ensures the accuracy of calculations.



### QUES - 5 : Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

### ANS - 5:

### **ndarrays in NumPy**

In NumPy, the primary data structure is the **ndarray** (short for **n-dimensional array**). It is a powerful, flexible, and efficient container for large datasets, particularly numerical data. An ndarray is a grid of values, all of the same type, indexed by a tuple of non-negative integers.

### **Key Features of ndarrays:**

1. **Homogeneous Data Type:**
   All elements in a NumPy array must have the same data type (e.g., integers, floats, etc.), which ensures efficient storage and computation.

2. **Fixed Size:**
   The size of an ndarray is fixed once it is created. This means that you cannot change the size of the array after its creation, but you can create new arrays with different sizes.

3. **Multidimensional:**
   ndarrays can represent multi-dimensional data structures, from simple 1D arrays to more complex 2D, 3D, and higher-dimensional arrays. This allows for efficient handling of multi-dimensional data, such as matrices or tensors.

4. **Vectorized Operations:**
   NumPy arrays support vectorized operations, which means operations are applied element-wise across entire arrays without the need for explicit loops. This leads to faster computations compared to standard Python lists.

5. **Efficient Memory Layout:**
   NumPy arrays are stored in contiguous memory blocks, allowing for efficient access and manipulation of data. This makes them much faster than Python lists, especially for large datasets.

6. **Broadcasting:**
   NumPy supports **broadcasting**, a mechanism that allows arrays of different shapes to be used together in operations, without needing to explicitly resize them. This enables more compact and efficient code.

7. **Mathematical and Statistical Functions:**
   NumPy provides a wide range of mathematical, statistical, and linear algebra functions that are optimized for performance, making it ideal for scientific computing and data analysis.

### **How ndarrays Differ from Standard Python Lists:**

1. **Data Type Homogeneity:**
   - **ndarrays:** All elements must be of the same data type (e.g., integers, floats).
   - **Python Lists:** Can store elements of different data types, such as integers, strings, and objects.

2. **Performance:**
   - **ndarrays:** Optimized for numerical operations, providing better performance for large datasets due to contiguous memory allocation and vectorized operations.
   - **Python Lists:** Slower when handling large datasets due to the lack of optimizations and the need for explicit loops for operations.

3. **Memory Efficiency:**
   - **ndarrays:** More memory efficient as they store data in a contiguous block and use less memory for numerical data types.
   - **Python Lists:** Less memory efficient because they store references to objects, and each element has additional overhead for data type and pointer storage.

4. **Multidimensional Support:**
   - **ndarrays:** Can handle multi-dimensional arrays (e.g., 2D, 3D), making them suitable for handling matrices, tensors, or other complex data structures.
   - **Python Lists:** Can be used to create lists of lists to represent multi-dimensional data, but this is inefficient and lacks the mathematical capabilities of ndarrays.

5. **Operations:**
   - **ndarrays:** Supports element-wise operations (e.g., addition, multiplication) directly without the need for explicit loops.
   - **Python Lists:** Requires loops or list comprehensions to perform operations element-wise.

### **Example of ndarray vs Python List:**

```python
import numpy as np

# Python List
py_list = [1, 2, 3, 4, 5]
print("Python List:", py_list)

# NumPy ndarray
np_array = np.array([1, 2, 3, 4, 5])
print("NumPy ndarray:", np_array)

# Element-wise operation (addition)
py_list_result = [x + 1 for x in py_list]  # Using list comprehension
np_array_result = np_array + 1  # Vectorized operation in NumPy

print("Python List Result:", py_list_result)
print("NumPy ndarray Result:", np_array_result)
```

**Output:**
```
Python List: [1, 2, 3, 4, 5]
NumPy ndarray: [1 2 3 4 5]
Python List Result: [2, 3, 4, 5, 6]
NumPy ndarray Result: [2 3 4 5 6]

### QUES - 6 :  Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

### ANS - 6 :

### **Performance Benefits of NumPy Arrays Over Python Lists for Large-Scale Numerical Operations**

NumPy arrays offer significant performance advantages over Python lists, especially when dealing with large-scale numerical operations. Below are the key aspects where NumPy arrays excel compared to standard Python lists:

### **1. Homogeneous Data Type vs. Heterogeneous Data Types**
- **NumPy arrays:** Store elements of the same data type, which allows for optimized memory usage and fast access. Since NumPy arrays are tightly packed in memory, they avoid the overhead associated with managing multiple data types.
- **Python lists:** Can hold elements of various data types (e.g., integers, floats, strings). This heterogeneity introduces additional memory overhead and complexity, slowing down operations.

**Performance Impact:**
- Homogeneous data types in NumPy allow better data alignment in memory, leading to faster operations, while Python lists need extra memory for managing different data types, which leads to slower access and operations.

### **2. Memory Efficiency**
- **NumPy arrays:** Store data in contiguous memory blocks, reducing memory overhead. The array structure ensures that elements are laid out in a uniform and compact manner, minimizing gaps in memory.
- **Python lists:** Store elements as pointers to objects, meaning each element requires additional space to store type information and pointers. This structure leads to less efficient memory usage.

**Performance Impact:**
- The memory layout of NumPy arrays allows for more compact data storage, leading to faster data access, less memory consumption, and better performance, especially when working with large datasets.

### **3. Vectorized Operations**
- **NumPy arrays:** Support vectorized operations, which allow for operations (e.g., addition, multiplication) to be performed element-wise without the need for explicit loops. NumPy uses highly optimized C and Fortran libraries for these operations.
- **Python lists:** Do not support vectorized operations. To perform element-wise operations, you would need to manually write loops or use list comprehensions, which is slower than NumPy's internal vectorized implementation.

**Performance Impact:**
- Vectorized operations in NumPy can execute thousands or even millions of operations in parallel at the CPU level, making NumPy much faster for large-scale computations. In contrast, Python list operations, using loops, are much slower because they are interpreted by Python one element at a time.

### **4. Broadcasting**
- **NumPy arrays:** Support **broadcasting**, a mechanism that allows NumPy to perform arithmetic operations on arrays of different shapes without the need for explicit resizing or replication of data. Broadcasting avoids the creation of unnecessary copies of arrays.
- **Python lists:** Do not support broadcasting. Operations between lists of different sizes or shapes require complex looping and manual handling.

**Performance Impact:**
- Broadcasting in NumPy makes operations on multi-dimensional arrays more efficient by eliminating the need for redundant copying of data, resulting in faster execution times for element-wise operations on large arrays.

### **5. Optimized Mathematical Functions**
- **NumPy arrays:** Provide a wide range of highly optimized mathematical functions (e.g., `np.add()`, `np.sum()`, `np.dot()`), many of which are implemented in C and run faster than native Python functions.
- **Python lists:** Lack built-in support for mathematical functions. Operations like summing or multiplying elements require looping through the list and manually applying operations.

**Performance Impact:**
- NumPy's mathematical functions are implemented in compiled languages (C, Fortran), making them much faster than Python's built-in functions, which are interpreted. This results in a significant speed boost when performing large-scale numerical operations.

### **6. Parallelism and Multi-threading**
- **NumPy arrays:** Many NumPy functions are optimized to utilize multiple cores of the CPU for parallel processing. Libraries like **BLAS** and **LAPACK** are used under the hood for matrix operations, which benefit from parallelism.
- **Python lists:** Do not natively support parallelism. To take advantage of multi-core processors, you would need to manually implement parallel processing techniques using Python's threading or multiprocessing libraries.

**Performance Impact:**
- NumPy's use of multi-core processors for large matrix operations allows for better utilization of hardware resources, leading to faster computations for large-scale problems.

### **7. Speed of Element Access**
- **NumPy arrays:** Use contiguous memory blocks, enabling faster access to elements. The data is stored in a format that makes it easy to access in bulk (e.g., entire rows, columns, or subarrays).
- **Python lists:** Store pointers to objects, which require additional dereferencing. Accessing each element in a Python list takes longer, as each element is a separate object.

**Performance Impact:**
- Faster element access in NumPy reduces the time spent retrieving data from memory, especially for large datasets. This is crucial when working with large-scale numerical operations.

### **8. Large-Scale Data Handling**
- **NumPy arrays:** Designed to handle large arrays and matrices efficiently. NumPy’s internal memory management and optimization allow it to work seamlessly with datasets that may not fit in standard Python lists.
- **Python lists:** Struggle with large datasets because of their inefficient memory allocation and slower performance during operations.

**Performance Impact:**
- NumPy is optimized for working with large datasets (e.g., large matrices, multi-dimensional arrays), while Python lists become increasingly inefficient as the data size grows, both in terms of memory usage and computation time.

### QUES - 7 :Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.

### ANS - 7 :
### **Comparison of `vstack()` and `hstack()` Functions in NumPy**

Both `vstack()` and `hstack()` are functions in NumPy used to stack arrays, but they differ in the direction in which they stack the arrays.

1. **`vstack()`**: This function stacks arrays **vertically** (row-wise), meaning it adds rows of one array to the rows of another array.

2. **`hstack()`**: This function stacks arrays **horizontally** (column-wise), meaning it adds columns of one array to the columns of another array.

---

### **1. `vstack()` - Stacking Vertically (Row-wise)**

The `vstack()` function takes arrays and stacks them along the **vertical axis (rows)**.

#### Syntax:
```python
numpy.vstack(tup)
```
- **tup**: A sequence of arrays to be stacked. The arrays must have the same number of columns.

#### Example:
```python
import numpy as np

# Creating two 2D arrays
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

# Stacking vertically
result = np.vstack((array1, array2))

print("Vertical Stack (vstack):")
print(result)
```

#### Output:
```
Vertical Stack (vstack):
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
```

In this example, `array2` is stacked below `array1`, resulting in a 4x2 array.

---

### **2. `hstack()` - Stacking Horizontally (Column-wise)**

The `hstack()` function takes arrays and stacks them along the **horizontal axis (columns)**.

#### Syntax:
```python
numpy.hstack(tup)
```
- **tup**: A sequence of arrays to be stacked. The arrays must have the same number of rows.

#### Example:
```python
import numpy as np

# Creating two 2D arrays
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

# Stacking horizontally
result = np.hstack((array1, array2))

print("Horizontal Stack (hstack):")
print(result)
```

#### Output:
```
Horizontal Stack (hstack):
[[1 2 5 6]
 [3 4 7 8]]
```

In this example, `array2` is stacked to the right of `array1`, resulting in a 2x4 array.

---

### **Key Differences:**
- **Direction**:
  - `vstack()`: Stacks arrays **vertically** (along rows).
  - `hstack()`: Stacks arrays **horizontally** (along columns).
  
- **Shape Compatibility**:
  - `vstack()`: Arrays must have the same number of columns.
  - `hstack()`: Arrays must have the same number of rows.

---

### **Conclusion:**
- Use **`vstack()`** when you need to append arrays by adding more rows.
- Use **`hstack()`** when you need to append arrays by adding more columns.

Both functions are commonly used in data processing and machine learning tasks when you need to merge or combine arrays.


### QUES - 8 :  Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.

### ANS - 8 : 

### **Differences Between `fliplr()` and `flipud()` Methods in NumPy**

The `fliplr()` and `flipud()` methods in NumPy are used to reverse the elements of an array, but they operate in different directions.

1. **`fliplr()`**:
   - **Effect**: The `fliplr()` function flips an array **left to right** (horizontally). It mirrors the elements of the array along the vertical axis (columns).
   - **Use case**: This method is commonly used when you want to reverse the order of the columns in a 2D array or flip the array horizontally.
   
   #### Syntax:
   ```python
   numpy.fliplr(arr)
   ```
   - **arr**: The input array to be flipped.

   #### Example (for a 2D array):
   ```python
   import numpy as np

   # Creating a 2D array
   arr = np.array([[1, 2, 3], [4, 5, 6]])

   # Flipping array left to right (horizontally)
   result = np.fliplr(arr)
   print(result)
   ```

   #### Output:
   ```
   [[3 2 1]
    [6 5 4]]
   ```

   In this example, the columns are reversed for each row of the array.

2. **`flipud()`**:
   - **Effect**: The `flipud()` function flips an array **up to down** (vertically). It mirrors the elements of the array along the horizontal axis (rows).
   - **Use case**: This method is used when you need to reverse the order of rows in a 2D array or flip the array vertically.
   
   #### Syntax:
   ```python
   numpy.flipud(arr)
   ```
   - **arr**: The input array to be flipped.

   #### Example (for a 2D array):
   ```python
   import numpy as np

   # Creating a 2D array
   arr = np.array([[1, 2, 3], [4, 5, 6]])

   # Flipping array up to down (vertically)
   result = np.flipud(arr)
   print(result)
   ```

   #### Output:
   ```
   [[4 5 6]
    [1 2 3]]
   ```

   In this example, the rows are reversed in order, so the first row becomes the last and vice versa.

---

### **Key Differences:**
1. **Axis of Reversal**:
   - `fliplr()`: Flips the array along the **vertical axis** (left to right).
   - `flipud()`: Flips the array along the **horizontal axis** (up to down).

2. **Effect on Array Dimensions**:
   - **For 1D arrays**:
     - `fliplr()` and `flipud()` will have the same effect because a 1D array only has one axis (either row or column), and flipping it horizontally or vertically results in the same reversed array.
   - **For 2D arrays**:
     - `fliplr()` reverses the elements along each row.
     - `flipud()` reverses the entire order of rows.

---

### **Effect on Higher Dimensions (3D arrays)**:
- **`fliplr()`**: Reverses each **2D slice** (i.e., flips arrays in the horizontal direction within the 3D array).
- **`flipud()`**: Reverses the entire **array stack** (i.e., flips arrays in the vertical direction within the 3D array).

Example:
import numpy as np

# Creating a 3D array (2x2x3)
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

# Flipping left to right (horizontally)
flipped_lr = np.fliplr(arr)
print("Flipped Left to Right (fliplr):")
print(flipped_lr)

# Flipping up to down (vertically)
flipped_ud = np.flipud(arr)
print("Flipped Up to Down (flipud):")
print(flipped_ud)
```


---

### **Conclusion:**
- Use **`fliplr()`** when you need to reverse the array horizontally (left to right).
- Use **`flipud()`** when you need to reverse the array vertically (up to down).
  

### QUES - 9 : Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

### ANS - 9:  

### **Functionality of `array_split()` Method in NumPy**

The `array_split()` function in NumPy is used to split an array into multiple sub-arrays. It is a flexible method that can divide the array into a specified number of sub-arrays along a particular axis. This is particularly useful when you need to break down large datasets into smaller, manageable pieces.

#### **Syntax:**
```python
numpy.array_split(ary, indices_or_sections, axis=0)
```

- **ary**: The array to be split.
- **indices_or_sections**: This can either be:
  - An integer representing the number of equal-sized sub-arrays to split the array into.
  - An array of indices along which to split.
- **axis**: The axis along which to split the array. The default is 0 (split along rows for a 2D array). If set to 1, it will split along columns.

---

### **How `array_split()` Handles Uneven Splits**

One of the key features of `array_split()` is its ability to handle uneven splits, which makes it more flexible compared to other split functions such as `split()`. When the array cannot be divided evenly into the specified number of sub-arrays, `array_split()` distributes the leftover elements across the sub-arrays as evenly as possible.

For example:
- If the number of elements is not divisible by the number of sub-arrays, `array_split()` will allocate the "extra" elements to the first few sub-arrays.

#### **Example 1: Split into Uneven Sub-arrays**

```python
import numpy as np

# Creating a 1D array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Splitting the array into 4 parts
result = np.array_split(arr, 4)

print("Split Array into 4 parts:")
for sub_arr in result:
    print(sub_arr)
```

#### Output:
```
Split Array into 4 parts:
[1 2]
[3 4]
[5 6]
[7 8 9]
```

In this case, the array has 9 elements, and it is split into 4 sub-arrays. The first three sub-arrays have 2 elements each, and the last sub-array has the remaining 3 elements.

---

#### **Example 2: Split 2D Array Along Axis 0 (Rows)**

```python
# Creating a 2D array (3x4)
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Splitting the array into 2 parts along rows
result_2d = np.array_split(arr_2d, 2, axis=0)

print("Split 2D Array into 2 parts along rows:")
for sub_arr in result_2d:
    print(sub_arr)
```

#### Output:
```
Split 2D Array into 2 parts along rows:
[[1 2 3 4]
 [5 6 7 8]]
[[ 9 10 11 12]]
```

Here, the 3x4 array is split along rows (axis 0), resulting in two sub-arrays: one with 2 rows and the other with 1 row.

---

#### **Example 3: Split 2D Array Along Axis 1 (Columns)**

```python
# Splitting the 2D array into 3 parts along columns
result_2d_cols = np.array_split(arr_2d, 3, axis=1)

print("Split 2D Array into 3 parts along columns:")
for sub_arr in result_2d_cols:
    print(sub_arr)
```

#### Output:
```
Split 2D Array into 3 parts along columns:
[[1 2]
 [5 6]
 [9 10]]
[[ 3 4]
 [ 7 8]
 [11 12]]
```

Here, the 3x4 array is split along columns (axis 1), resulting in three sub-arrays, each with 2 columns.

---

### **Key Points:**
1. **Uneven Splits**:
   - When the number of elements in the array is not divisible by the number of sub-arrays requested, the remaining elements are distributed as evenly as possible across the sub-arrays.
   - This means that the first few sub-arrays might have one extra element compared to the others.

2. **Flexible Axis**:
   - You can specify the axis along which the array should be split. By default, it is 0 (split along rows), but you can change it to 1 to split along columns.

3. **Handling of Non-even Divisions**:
   - Unlike `split()`, which requires an even division of the array, `array_split()` is much more flexible and handles cases where the array can't be evenly divided, thus allowing for uneven splits.

4. **Return Type**:
   - The result of `array_split()` is always a list of sub-arrays (as opposed to `split()`, which returns a tuple of arrays).

---

### **Conclusion:**
The `array_split()` function is extremely useful for splitting arrays into smaller parts in cases where an even division is not possible. It intelligently handles the distribution of remaining elements, making it ideal for applications in data processing where uneven splits are common (e.g., dividing data into training and test sets).

### QUES - 10 :Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?

### ANS - 10 : 

### **Concepts of Vectorization and Broadcasting in NumPy**

Both **vectorization** and **broadcasting** are key concepts in NumPy that contribute significantly to the efficiency of array operations. They allow operations on arrays to be performed much faster than traditional loops in Python. Let's explore each concept in detail:

---

### **1. Vectorization in NumPy**

**Vectorization** refers to the process of applying an operation on an entire array (or multiple arrays) without the need for explicit loops in Python. Instead of iterating through array elements individually using a loop, NumPy allows you to perform operations on whole arrays in a more efficient manner.

#### **How Vectorization Works:**
- When you perform operations (e.g., addition, multiplication) on NumPy arrays, it utilizes optimized **C** libraries behind the scenes. These operations are implemented in highly efficient machine code, which is faster than Python's regular for-loop operations.
- This leads to **element-wise operations** on arrays without the need for Python-level loops, improving performance.

#### **Example:**
```python
import numpy as np

# Creating two NumPy arrays
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([10, 20, 30, 40])

# Using vectorization for element-wise addition
result = arr1 + arr2
print(result)
```

#### Output:
```
[11 22 33 44]
```

In this example, the addition operation `arr1 + arr2` is vectorized, meaning that it operates on the entire arrays directly, without explicit iteration over the elements.

#### **Benefits of Vectorization:**
- **Performance**: Vectorized operations are implemented in C and are much faster than Python loops.
- **Simplicity**: You can write cleaner and more concise code without needing explicit loops.
- **Readability**: The code becomes more readable and closer to mathematical notation.

---

### **2. Broadcasting in NumPy**

**Broadcasting** is a powerful feature in NumPy that allows operations on arrays of different shapes and sizes. It refers to how NumPy handles element-wise operations between arrays that have incompatible shapes. Instead of requiring arrays to have the same dimensions, broadcasting enables NumPy to "stretch" the smaller array to match the shape of the larger array, so that operations can be performed between them.

#### **How Broadcasting Works:**
- When performing operations between arrays of different shapes, NumPy automatically **broadcasts** the smaller array to match the shape of the larger array.
- Broadcasting follows a set of rules to decide how arrays with different shapes can be aligned for element-wise operations.
  1. **Rule 1**: If the arrays have a different number of dimensions, the smaller array is padded with ones on the left side until both arrays have the same number of dimensions.
  2. **Rule 2**: If the size of an array along a particular dimension is not equal to the size of the other array, the array with size 1 in that dimension is stretched (broadcasted) to match the size of the other array.

#### **Example of Broadcasting:**

```python
import numpy as np

# Creating a 2D array (3x4)
arr1 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12]])

# Creating a 1D array (4,)
arr2 = np.array([1, 2, 3, 4])

# Broadcasting arr2 to match the shape of arr1 and adding
result = arr1 + arr2
print(result)
```

#### Output:
```
[[ 2  4  6  8]
 [ 6  8 10 12]
 [10 12 14 16]]
```

In this example:
- `arr2` is a 1D array with shape (4,). 
- `arr1` is a 2D array with shape (3, 4). 
- **Broadcasting** allows the 1D array `arr2` to be added to each row of the 2D array `arr1` by "stretching" `arr2` to match the shape of `arr1`.

#### **Benefits of Broadcasting:**
- **Memory Efficiency**: Broadcasting allows operations on arrays of different shapes without explicitly creating large temporary arrays. Instead of replicating data, NumPy just aligns the arrays for efficient computation.
- **Flexibility**: You can perform operations on arrays of different shapes without having to reshape or replicate them manually.
- **Performance**: Broadcasting avoids the overhead of loops and uses highly optimized routines for the operation, speeding up the computations.

---

### **Comparison of Vectorization and Broadcasting**

- **Vectorization** is about applying operations on entire arrays (or arrays of the same shape) at once, avoiding loops.
- **Broadcasting** enables operations between arrays of different shapes by aligning them according to specific rules, making element-wise operations possible on arrays of different shapes.

---

### **Summary of Contributions to Efficient Array Operations**

1. **Vectorization**:
   - Eliminates the need for explicit loops.
   - Executes operations on entire arrays at once, leveraging optimized low-level code.
   - Results in faster and more readable code.
   
2. **Broadcasting**:
   - Allows operations on arrays with different shapes, avoiding the need to manually adjust shapes.
   - Efficiently uses memory by not creating unnecessary copies of data.
   - Speeds up operations on differently shaped arrays and reduces the complexity of reshaping arrays.

Both vectorization and broadcasting make NumPy a highly efficient library for numerical computations, especially when working with large datasets or performing operations on multi-dimensional arrays. They enable you to write concise, fast, and memory-efficient code, making them essential tools in scientific computing and data analysis.

################

## Practical Questions:

### QUES - 1 : Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.


In [1]:
### ANS - 1:

import numpy as np

# Creating a 3x3 NumPy array with random integers between 1 and 100
array = np.random.randint(1, 101, size=(3, 3))

# Displaying the original array
print("Original Array:")
print(array)

# Interchanging rows and columns (Transpose)
transposed_array = array.T

# Displaying the transposed array
print("\nTransposed Array (Rows and Columns Interchanged):")
print(transposed_array)

Original Array:
[[84 92 68]
 [36 64 39]
 [37 84 14]]

Transposed Array (Rows and Columns Interchanged):
[[84 36 37]
 [92 64 84]
 [68 39 14]]


### QUES - 2 :  Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [2]:
### ANS - 2:

import numpy as np

# Generating a 1D NumPy array with 10 elements
array_1d = np.arange(1, 11)  # Creates an array with values 1 to 10

# Reshaping the array into a 2x5 array
array_2x5 = array_1d.reshape(2, 5)

# Reshaping the array into a 5x2 array
array_5x2 = array_1d.reshape(5, 2)

# Displaying the reshaped arrays
print("Original 1D Array:")
print(array_1d)

print("\nReshaped 2x5 Array:")
print(array_2x5)

print("\nReshaped 5x2 Array:")
print(array_5x2)


Original 1D Array:
[ 1  2  3  4  5  6  7  8  9 10]

Reshaped 2x5 Array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

Reshaped 5x2 Array:
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


### QUES - 3 : Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [3]:
### ANS - 3 : 

import numpy as np

# Create a 4x4 array with random float values
array_4x4 = np.random.rand(4, 4)

# Add a border of zeros around the array to create a 6x6 array
array_with_border = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)

# Display the resulting array
print("Original 4x4 Array with Random Floats:")
print(array_4x4)

print("\nArray with Border (6x6):")
print(array_with_border)


Original 4x4 Array with Random Floats:
[[0.56818177 0.04425886 0.18426898 0.19830636]
 [0.3150842  0.94768923 0.93903468 0.54186943]
 [0.82838917 0.08782322 0.93538239 0.4154741 ]
 [0.15658975 0.70062517 0.90566159 0.28301716]]

Array with Border (6x6):
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.56818177 0.04425886 0.18426898 0.19830636 0.        ]
 [0.         0.3150842  0.94768923 0.93903468 0.54186943 0.        ]
 [0.         0.82838917 0.08782322 0.93538239 0.4154741  0.        ]
 [0.         0.15658975 0.70062517 0.90566159 0.28301716 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [4]:
### QUES - 4 :  Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [5]:
### ANS - 4:
import numpy as np

# Create an array from 10 to 60 with a step of 5
array = np.arange(10, 61, 5)

# Display the array
print(array)


[10 15 20 25 30 35 40 45 50 55 60]


### QUES - 5 :  Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

In [6]:
### ANS - 5:

import numpy as np

# Create a NumPy array of strings
arr = np.array(['python', 'numpy', 'pandas'])

# Apply uppercase transformation
uppercase = np.char.upper(arr)

# Apply lowercase transformation
lowercase = np.char.lower(arr)

# Apply title case transformation
title_case = np.char.title(arr)

# Apply swap case transformation (uppercase letters become lowercase and vice versa)
swap_case = np.char.swapcase(arr)

# Print results
print("Original Array:", arr)
print("Uppercase Transformation:", uppercase)
print("Lowercase Transformation:", lowercase)
print("Title Case Transformation:", title_case)
print("Swap Case Transformation:", swap_case)

Original Array: ['python' 'numpy' 'pandas']
Uppercase Transformation: ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase Transformation: ['python' 'numpy' 'pandas']
Title Case Transformation: ['Python' 'Numpy' 'Pandas']
Swap Case Transformation: ['PYTHON' 'NUMPY' 'PANDAS']


### QUES - 6 : Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [7]:
### ANS - 6:

import numpy as np

# Create a NumPy array of words
words = np.array(['python', 'numpy', 'pandas'])

# Insert a space between each character of every word
spaced_words = np.char.add(' ', words)  # Add space before each word
spaced_words = np.char.add(np.char.array(['' for _ in words]), spaced_words)  # Remove the extra space at the start

# Print the result
print("Original Words:", words)
print("Words with spaces between characters:", spaced_words)


Original Words: ['python' 'numpy' 'pandas']
Words with spaces between characters: [' python' ' numpy' ' pandas']


### QUES - 7 :  Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [8]:
### ANS - 7 :
import numpy as np

# Create two 2D NumPy arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[6, 5, 4], [3, 2, 1]])

# Element-wise addition
add_result = np.add(array1, array2)

# Element-wise subtraction
sub_result = np.subtract(array1, array2)

# Element-wise multiplication
mul_result = np.multiply(array1, array2)

# Element-wise division
div_result = np.divide(array1, array2)

# Print the results
print("Array 1:\n", array1)
print("Array 2:\n", array2)
print("\nElement-wise Addition:\n", add_result)
print("\nElement-wise Subtraction:\n", sub_result)
print("\nElement-wise Multiplication:\n", mul_result)
print("\nElement-wise Division:\n", div_result)


Array 1:
 [[1 2 3]
 [4 5 6]]
Array 2:
 [[6 5 4]
 [3 2 1]]

Element-wise Addition:
 [[7 7 7]
 [7 7 7]]

Element-wise Subtraction:
 [[-5 -3 -1]
 [ 1  3  5]]

Element-wise Multiplication:
 [[ 6 10 12]
 [12 10  6]]

Element-wise Division:
 [[0.16666667 0.4        0.75      ]
 [1.33333333 2.5        6.        ]]


### QUES - 8 : Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [9]:
### ANS - 8 :

import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Extract diagonal elements
diagonal_elements = np.diagonal(identity_matrix)

# Print the results
print("5x5 Identity Matrix:\n", identity_matrix)
print("\nDiagonal Elements:", diagonal_elements)


5x5 Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements: [1. 1. 1. 1. 1.]


### QUES - 9 :  Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

In [10]:
### ANS - 9 :

import numpy as np

# Step 1: Generate a NumPy array of 100 random integers between 0 and 1000
random_integers = np.random.randint(0, 1001, 100)

# Step 2: Function to check if a number is prime
def is_prime(num):
    if num <= 1:
        return False
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            return False
    return True

# Step 3: Filter out the prime numbers from the array
prime_numbers = [num for num in random_integers if is_prime(num)]

# Display the result
print("Prime Numbers in the Array:", prime_numbers)


Prime Numbers in the Array: [401, 233, 751, 107, 193, 37, 17, 367, 307, 997, 593, 181, 593, 593, 977, 19, 419, 863, 149]


### QUES - 10 :  Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages

In [11]:
### ANS - 10: 

import numpy as np

# Step 1: Generate daily temperatures for a month (28 days, 4 weeks)
daily_temperatures = np.random.randint(15, 35, 28)  # Temperatures between 15 and 35 degrees

# Step 2: Reshape the array into a 4x7 array (4 weeks and 7 days)
weekly_temperatures = daily_temperatures.reshape(4, 7)

# Step 3: Calculate the weekly averages
weekly_averages = np.mean(weekly_temperatures, axis=1)

# Display the results
print("Daily Temperatures for the Month:", daily_temperatures)
print("\nWeekly Temperatures (4 weeks x 7 days):")
print(weekly_temperatures)
print("\nWeekly Averages:", weekly_averages)


Daily Temperatures for the Month: [33 25 17 29 19 24 26 17 30 23 28 27 15 20 24 34 21 29 22 21 18 20 26 26
 19 22 26 32]

Weekly Temperatures (4 weeks x 7 days):
[[33 25 17 29 19 24 26]
 [17 30 23 28 27 15 20]
 [24 34 21 29 22 21 18]
 [20 26 26 19 22 26 32]]

Weekly Averages: [24.71428571 22.85714286 24.14285714 24.42857143]
